# Fixtures file hold the dependencies for spec helper

fixtures:
  forge_modules:
    stdlib:
     repo: "puppetlabs/stdlib"
     ref: "4.3.2"
    postgresql:
      repo: "puppetlabs/postgresql"
      ref: "4.1.0"
#    xinetd:
#      repo: "puppetlabs/xinetd"
#      ref: "1.3.1"
    vcsrepo:
      repo: "puppetlabs/vcsrepo"
      ref: "1.2.0"  
#    apt:
#      repo: "puppetlabs/apt"
#      ref: "1.7.0"  
    concat:
      repo: "puppetlabs/concat"
      ref: "1.1.2"
      
  repositories:
#    nfs: 
#      repo: "https://github.com/[USER]/[MODULE].git"
#      branch: "[BRANCH]"

  symlinks:
    razor: "#{source_dir}"