# Fixtures file hold the dependencies for spec helper

fixtures:
  forge_modules:
    stdlib:
     repo: "puppetlabs/stdlib"
     ref: "4.3.2"
    postgresql:
      repo: "puppetlabs/postgresql"
      ref: "4.1.0"
    vcsrepo:
      repo: "puppetlabs/vcsrepo"
      ref: "1.2.0"  
    concat:
      repo: "puppetlabs/concat"
      ref: "1.1.2"
    xinetd:
      repo: "puppetlabs/xinetd"
      ref: "1.3.1"
    wget:
      repo: "maestrodev/wget"
      ref: "1.5.6"  

  repositories:
    archive:
      repo: "https://github.com/lavaburn/puppet-archive.git"
      branch: "0.2.0-1"
    tftp:
      repo: "https://github.com/lavaburn/puppetlabs-tftp.git"
      branch: "0.2.2-1"

  symlinks:
    razor: "#{source_dir}"