---
language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
script: bundle exec rake test
jobs:
  include:
  - rvm: 2.1.9
    env: PUPPET_VERSION="~> 4.10.11" STRICT_VARIABLES=yes
  include:
  - rvm: 2.4.9
    env: PUPPET_VERSION="~> 5.5.22" STRICT_VARIABLES=yes
  include:
  - rvm: 2.5.7
    env: PUPPET_VERSION="~> 6.21.1" STRICT_VARIABLES=yes
  include:
  - rvm: 2.7.2
    env: PUPPET_VERSION="~> 7.5.0" STRICT_VARIABLES=yes
