---
language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
rvm:
  - 1.8.7
  - 1.9.3
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 3.4.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.6.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.7.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.0.0" STRICT_VARIABLES=yes
matrix:
  exclude:
  - rvm: 1.8.7
    env: PUPPET_VERSION="~> 4.0.0"
