HOSTS:
  ubuntu-14-04:
    roles:
      - master
      - agent
    platform: ubuntu-14.04-x64
    box: puppetlabs/ubuntu-14.04-64-puppet
    box_url: https://vagrantcloud.com/puppetlabs/boxes/ubuntu-14.04-64-puppet
    hypervisor: vagrant
CONFIG:
  type: foss